// 边距
export const PADDING_S = 10
export const PADDING = 16
export const PADDING_L = 20

// 圆角
export const BORDER_RADIUS_S = 4
export const BORDER_RADIUS = 8
export const BORDER_RADIUS_L = 12

// 阴影
export const SHADOW_RADIUS = 7.8

// 字体
export const FONT_SIZE_M = 10
export const FONT_SIZE_S = 12
export const FONT_SIZE = 14
export const FONT_SIZE_L = 16
export const FONT_SIZE_ML = 20

// tab 内容距离下边框的高度
export const OFFSET_BOTTOM = 100
